name: 'Moes Star Ring Thermostat'
packageKey: 'moes-star-thermostat'
permissions:
  zigbee: {}
profiles:
  - id: "thermostat-profile"
    deviceLabel: "Moes Star Ring Thermostat"
    manufacturer: "_TZE204_IPEDVTVR"
    model: "TS0601"
    deviceProfileName: thermostat
    metadata:
      ocfDeviceType: "oic.d.thermostat"
      deviceType: "Thermostat"
      mnmn: "SmartThings"
      vid: "generic-thermostat"
    components:
      - id: "main"
        capabilities:
          - id: "thermostatMode"
            version: 1
          - id: "thermostatHeatingSetpoint"
            version: 1
          - id: "temperatureMeasurement"
            version: 1
          - id: "battery"
            version: 1
          - id: "refresh"
            version: 1
        categories:
          - name: "Thermostat"
fingerprints:
  - id: "moes-star-ring-thermostat"
    deviceLabel: "Moes Star Ring Thermostat"
    manufacturer: "_TZE204_IPEDVTVR"
    model: "TS0601"
    deviceProfileName: thermostat
