name: 'Moes Star Ring Thermostat'
packageKey: 'moes-star-thermostat'
permissions:
  zigbee: {}
fingerprints:
  - id: "moes-star-ring-thermostat"
    deviceLabel: "Moes Star Ring Thermostat"
    manufacturer: "_TZE204_IPEDVTVR"
    model: "TS0601"
    deviceProfileName: moes-thermostat
