name: 'Moes Star Ring Thermostat'
packageKey: 'moes-star-thermostat'
permissions:
  zigbee: {}
profiles:
  - id: "moes-thermostat"
    deviceLabel: "Moes Star Ring Thermostat"
    manufacturer: "_TZE204_lpedvtvr"
    model: "TS0601"
    deviceProfileName: moes-thermostat
